<?php
// $Id: xoops_version.php,v 1.11 2006/06/09 14:32:47 mithyt2 Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
$modversion['name'] = "Competitions";
$modversion['version'] = 0.03;
$modversion['versionstatus'] = "alpha";
$modversion['description'] = "TripleA Competition Module";
$modversion['credits'] = "The XOOPS Project";
//$modversion['help'] = "team.html";
//$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['author'] = "Andreas Menrath aka Clausewitz";
$modversion['image'] = "images/comp.png";
$modversion['dirname'] = "comp";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "comp_admins";
$modversion['tables'][1] = "comp_challenges";
$modversion['tables'][3] = "comp_competitions";
$modversion['tables'][4] = "comp_invitations";
$modversion['tables'][5] = "comp_matches";
$modversion['tables'][6] = "comp_rating";
$modversion['tables'][7] = "comp_user_global";
$modversion['tables'][8] = "comp_user_local";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";



// Blocks
$modversion['blocks'][1] = array(
	'file' => "comp_nav.php",
	'name' => "TripleA Comp Menu",
	'description' => "Shows menu",
	'show_func' => "comp_menu_show",
	'template' => "comp_menu.html");
/*
	$modversion['blocks'][2]['file'] = "comp_nav.php";
	$modversion['blocks'][2]['name'] = "TripleA Competitions";
	$modversion['blocks'][2]['description'] = "Shows Competitions for TripleA";
	$modversion['blocks'][2]['show_func'] = "nav_menu";
*/



// Menu
$modversion['hasMain'] = 1;
/*
$modversion['sub'][1]['name'] = _MI_MATCH_SMNAME2;
$modversion['sub'][1]['url'] = "index.php";
$modversion['sub'][2]['name'] = _MI_MATCH_SMNAME3;
$modversion['sub'][2]['url'] = "roster.php";
$modversion['sub'][3]['name'] = _MI_MATCH_SMNAME4;
$modversion['sub'][3]['url'] = "tactics.php";
*/

// Templates
$modversion['templates'][0]['file'] = 'comp_index.html';
$modversion['templates'][0]['description'] = 'comp Template Page';
$modversion['templates'][1]['file'] = 'comp_sandbox.html';
$modversion['templates'][1]['description'] = 'comp Sandbox';
$modversion['templates'][2]['file'] = 'comp_rules.html';
$modversion['templates'][2]['description'] = 'comp Rules Page';
$modversion['templates'][3]['file'] = 'standings.html';
$modversion['templates'][3]['description'] = 'comp Standings Page';
$modversion['templates'][4]['file'] = 'profile.html';
$modversion['templates'][4]['description'] = 'comp Player Profile Page';
$modversion['templates'][5]['file'] = 'players.html';
$modversion['templates'][5]['description'] = 'comp Competition Player List Page';
$modversion['templates'][6]['file'] = 'matches.html';
$modversion['templates'][6]['description'] = 'comp Competition Match Page';
$modversion['templates'][7]['file'] = 'challenges.html';
$modversion['templates'][7]['description'] = 'comp Competition Challenge List Page';
$modversion['templates'][8]['file'] = 'searchresults.html';
$modversion['templates'][8]['description'] = 'comp Competition Searchresults Page';
$modversion['templates'][9]['file'] = 'ratings.html';
$modversion['templates'][9]['description'] = 'comp Ratings Display Page';
$modversion['templates'][10]['file'] = 'invitationresults.html';
$modversion['templates'][10]['description'] = 'comp Invitation Search Results';
?>